// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoUDw6OuN8eSU0ouWgun8nReAc8I5lt2M',
    appId: '1:333165744649:web:abd8a59e00c09dbbfc5ed8',
    messagingSenderId: '333165744649',
    projectId: 'sudsolver-19a46',
    authDomain: 'sudsolver-19a46.firebaseapp.com',
    storageBucket: 'sudsolver-19a46.firebasestorage.app',
    measurementId: 'G-2LF0TCVMPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-LqfyFTdoqcpYUfide4jYDF_neSLrEXU',
    appId: '1:333165744649:android:cd8fbe90ba522834fc5ed8',
    messagingSenderId: '333165744649',
    projectId: 'sudsolver-19a46',
    storageBucket: 'sudsolver-19a46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARgTvQ2TY8kKiNtwBLMfnbCoWRp7Un-nc',
    appId: '1:333165744649:ios:1f763adbcd713618fc5ed8',
    messagingSenderId: '333165744649',
    projectId: 'sudsolver-19a46',
    storageBucket: 'sudsolver-19a46.firebasestorage.app',
    iosBundleId: 'com.github.mihvv.sudsolver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARgTvQ2TY8kKiNtwBLMfnbCoWRp7Un-nc',
    appId: '1:333165744649:ios:27c7a60d564c36d6fc5ed8',
    messagingSenderId: '333165744649',
    projectId: 'sudsolver-19a46',
    storageBucket: 'sudsolver-19a46.firebasestorage.app',
    iosBundleId: 'com.example.sudsolver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoUDw6OuN8eSU0ouWgun8nReAc8I5lt2M',
    appId: '1:333165744649:web:b0ae02cb8a00e2c4fc5ed8',
    messagingSenderId: '333165744649',
    projectId: 'sudsolver-19a46',
    authDomain: 'sudsolver-19a46.firebaseapp.com',
    storageBucket: 'sudsolver-19a46.firebasestorage.app',
    measurementId: 'G-R9PFCLMSR9',
  );
}
