// Mocks generated by Mockito 5.4.4 from annotations
// in sudsolver/test/backend/backend_api_mock_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:sudsolver/backend/models/sudoku_record.dart' as _i4;
import 'package:sudsolver/backend/repositories/firestore_sudoku_repository.dart'
    as _i5;
import 'package:sudsolver/backend/repositories/sudoku_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ISudokuRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockISudokuRepository extends _i1.Mock implements _i2.ISudokuRepository {
  MockISudokuRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> save(_i4.SudokuRecord? record) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [record],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.SudokuRecord>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.SudokuRecord>>.value(<_i4.SudokuRecord>[]),
      ) as _i3.Future<List<_i4.SudokuRecord>>);

  @override
  _i3.Future<_i4.SudokuRecord?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i3.Future<_i4.SudokuRecord?>.value(),
      ) as _i3.Future<_i4.SudokuRecord?>);

  @override
  _i3.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [FirestoreSudokuRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreSudokuRepository extends _i1.Mock
    implements _i5.FirestoreSudokuRepository {
  MockFirestoreSudokuRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get uid => (super.noSuchMethod(
        Invocation.getter(#uid),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#uid),
        ),
      ) as String);

  @override
  _i3.Future<void> save(_i4.SudokuRecord? record) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [record],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.SudokuRecord>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.SudokuRecord>>.value(<_i4.SudokuRecord>[]),
      ) as _i3.Future<List<_i4.SudokuRecord>>);

  @override
  _i3.Future<_i4.SudokuRecord?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i3.Future<_i4.SudokuRecord?>.value(),
      ) as _i3.Future<_i4.SudokuRecord?>);

  @override
  _i3.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> uploadBatch(List<_i4.SudokuRecord>? records) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadBatch,
          [records],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
