name: Build
run-name: Build profile APK for ${{ github.ref_name }}

on:
  push:
    branches: [main, backend]
    paths-ignore:
      - "README.md"
      - "**/*.md"
      - "**/*.yaml"

jobs:
  build:
    name: Build profile APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: ex_br

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.41.9
          channel: stable

      - name: Flutter pub get
        run: |
          flutter config --no-analytics
          flutter pub get

      - name: Create keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/keystore.jks

      - name: Debug keystore SHA1
        run: |
          keytool -list -v -keystore android/app/keystore.jks \
          -alias ${{ secrets.KEY_ALIAS }} \
          -storepass ${{ secrets.STORE_PASSWORD }} \
          | grep SHA1

      - name: Create key.properties
        run: |
          echo "storeFile=keystore.jks"                        > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}"  >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}"      >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}"            >> android/key.properties

      - name: Modify app metadata (Debug branding)
        run: |
          sed -i 's/applicationId = "com.github.mihvv.sudsolver"/applicationId = "com.github.mihvv.sudsolver.debug"/g' android/app/build.gradle*
          sed -i 's/android:label="SudSolver"/android:label="Sudsolver (${{ steps.ex_br.outputs.branch }})"/g' android/app/src/main/AndroidManifest.xml

      - name: Create google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d > android/app/google-services.json

      - name: Debug google-services.json
        run: |
          cat android/app/google-services.json | grep certificate_hash

      - name: Build profile APK
        run: |
          flutter build apk --profile --build-number=${{ github.run_number }}

      - name: Upload to Firebase App Distribution
        uses: w9jds/firebase-action@master
        with:
          args: appdistribution:distribute build/app/outputs/flutter-apk/app-profile.apk --app ${{ secrets.FIREBASE_APP_ID }} --groups "testers"
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-profile-${{ steps.ex_br.outputs.branch }}
          path: build/app/outputs/flutter-apk/app-profile.apk
          retention-days: 14
