name: Build
run-name: Build debug apks for ${{ github.ref_name }}

on:
  push:
    branches: [main, backend, cicd]
    paths-ignore:
      - "README.md"
      - "**/*.md"
      - "**/*.yaml"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Analyze and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: ex_br

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.41.9
          channel: stable

      - name: Create keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/keystore.jks

      - name: Create key.properties
        run: |
          echo "storeFile=keystore.jks" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      - name: Modify app metadata (Debug branding)
        run: |
          sed -i 's/applicationId = "com.github.mihvv.sudsolver"/applicationId = "com.github.mihvv.sudsolver.debug"/g' android/app/build.gradle*
          sed -i 's/android:label="SudSolver"/android:label="Sudsolver (debug)"/g' android/app/src/main/AndroidManifest.xml

      - name: Create google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d > android/app/google-services.json

      - name: Flutter preparation
        run: |
          flutter config --no-analytics
          flutter pub get

      - name: Analyze code
        run: |
          dart format --output=none --set-exit-if-changed ./lib
          dart analyze --no-fatal-warnings ./lib

      - name: Run unit tests
        run: flutter test

      - name: Build profile APK
        run: flutter build apk --profile

      - name: Upload to Firebase App Distribution
        uses: w9jds/firebase-action@master
        with:
          args: appdistribution:distribute build/app/outputs/flutter-apk/app-profile.apk --app ${{ secrets.FIREBASE_APP_ID }} --groups "testers"
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-profile-${{ steps.ex_br.outputs.branch }}
          path: build/app/outputs/flutter-apk/app-profile.apk
