name: Release a new version
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Flutter Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.41.0
          channel: stable

      - name: Create Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/keystore.jks
          echo "storeFile=keystore.jks" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      - name: Build Apps
        run: |
          flutter pub get
          flutter build apk --split-per-abi
          flutter build apk
          flutter build appbundle

      - name: Prepare Files
        run: |
          mkdir -p release-artifacts
          cp build/app/outputs/flutter-apk/app-release.apk release-artifacts/sudsolver-full.apk
          cp build/app/outputs/bundle/release/app-release.aab release-artifacts/sudsolver.aab

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-artifacts/*.apk
            release-artifacts/*.aab
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
